### ISSUE TITLE
Assignment Progress

### ISSUE THREAD

**Issue by dluman** [term-world/woodshop-solution#5]
# `TODO`s

Based on the GatorGrader report for this run, here's a summary of what you've got left to do.

## Reflection

- [ ] No TODO markers left in reflection.md
- [x] reflection.md responds to all questions
- [x] reflection.md contains at least 350 words

## WoodPile Woes

- [x] No TODO markers left in WoodPile.py
- [x] WoodPile.py constructor takes no explicit arguments
- [x] WoodPile.py constructor creates an empty list property called pieces
- [x] WoodPile.py add method takes one explicit parameter
- [x] WoodPile.py add method adds the list of Lumber objects to ongoing pieces list

## Lumber Labor

- [x] No TODO markers left in Lumber.py
- [x] Lumber.py constructor takes 2 parameters
- [x] Lumber.py constructor sets the length property

## Didja See the Saw?

- [x] Saw.py contains at least one comment for each method

## Main Mission

- [x] main.py imports Saw correctly
- [x] main.py imports WoodPile correctly
- [x] main.py imports Lumber correctly
- [x] main.py creates a Saw object
- [x] main.py creates a WoodPile object
- [x] main.py creates Lumber objects
- [x] main.py adds to the WoodPile
- [x] main.py uses the Saw
- [x] main.py calls Plans with list of WoodPile pieces as argument

## Did it Build?

- [x] Chair.py exists in the products&#x2F;
- [x] Table.py exists in the products&#x2F;
- [x] Bookshelf.py exists in the products&#x2F;

## Percent complete

Based on the checks achieved, this assignment is `95%` complete.
